import React from "react"
import data from "@/app/all-blog/InputData"
import UserInfo from "./UserInfo"
import { Badge } from "@/components/ui/badge"

const Page = ({ params }: { params: { name: string } }) => {
  const { name } = params
  const urlName = name.replaceAll("-", " ")
  const filteredData = data.filter((item) => item.title === urlName)
  const { title, description, category } = filteredData[0]

  return (
    <section className="w-full h-[90vh] flex flex-col gap-5 items-center py-8 ">
      <UserInfo data={filteredData} />
      <hr className="w-1/2" />
      <section className="w-1/2 flex flex-col gap-3">
        <h1 className="text-3xl font-semibold">{title}</h1>

        <div className="flex gap-2 -mt-2">
          {category.map((item, index) => {
            return (
              <div key={index}>
                <Badge variant="secondary" className="font-normal">
                  # {item}
                </Badge>
              </div>
            )
          })}
        </div>

        <div className="w-full border-2 h-[300px] rounded-lg flex justify-center items-center">
          <h1 className="opacity-30">
            Title based black/white image generated by ai (future update)
          </h1>
        </div>

        <p className="opacity-80">{description}</p>
      </section>
    </section>
  )
}

export default Page
